version: '2'

services:

    shared-data:
        build: shared-data
        hostname: shared-data

    koji-db:
        build: koji-db
        hostname: koji-db
        environment:
            - POSTGRES_DB=koji
            - POSTGRES_USER=koji
            - POSTGRES_PASSWORD=mypassword

    koji-hub:
        build: hub
        hostname: koji-hub
        volumes:
            - /opt/koji:/opt/koji:rw
            - /opt/koji-clients:/opt/koji-clients:rw
        links:
            - koji-db

    koji-client:
        build: client
        hostname: koji-client
        volumes_from:
            - koji-hub:rw
        links:
            - koji-hub

